<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import dayjs from 'dayjs'
import { ElMessage, ElMessageBox } from 'element-plus'
import type { AxiosError } from 'axios'
import { batchCreateSchedules, confirmSchedule, copyScheduleWeek, createSchedule, deleteSchedule, getSchedules, moveSchedule, rejectSchedule, submitSchedule, updateSchedule } from '@/api/schedule'
import { getProjects } from '@/api/project'
import { getTasks } from '@/api/task'
import { getUserOptions } from '@/api/user'
import { getDepartmentOptions } from '@/api/organization'
import ScheduleTimelineHeader from '@/components/schedule/ScheduleTimelineHeader.vue'
import UserScheduleRow from '@/components/schedule/UserScheduleRow.vue'
import ScheduleBookingDialog from '@/components/schedule/ScheduleBookingDialog.vue'
import ScheduleConflictDialog from '@/components/schedule/ScheduleConflictDialog.vue'
import type { ApiResponse } from '@/types/common'
import type { DepartmentOption } from '@/types/organization'
import type { Project } from '@/types/project'
import type { Schedule, ScheduleBatchPayload, ScheduleConflict, SchedulePayload } from '@/types/schedule'
import type { Task } from '@/types/task'
import type { UserOption } from '@/types/user'
import { formatDateTime } from '@/utils/format'
import { useUserStore } from '@/stores/user'

const userStore=useUserStore(),loading=ref(false),viewMode=ref<'day'|'week'|'month'>('week'),anchorDate=ref(dayjs().format('YYYY-MM-DD'))
const schedules=ref<Schedule[]>([]),projects=ref<Project[]>([]),tasks=ref<Task[]>([]),users=ref<UserOption[]>([]),departments=ref<DepartmentOption[]>([])
const filter=reactive({project_id:undefined as number|undefined,user_id:undefined as number|undefined,department_id:undefined as number|undefined})
const bookingDialog=ref(false),detailDialog=ref(false),conflictDialog=ref(false),batchDialog=ref(false),batchSaving=ref(false)
const selected=ref<Schedule>(),initialSlot=ref<{userId:number;date:string;hour:number}>(),conflicts=ref<ScheduleConflict[]>([])
const batchForm=reactive<ScheduleBatchPayload>({user_ids:[],project_id:0,task_id:0,start_time:'',end_time:'',remark:''})
const cellWidth=56
const hours=computed(()=>viewMode.value==='day'?Array.from({length:24},(_,i)=>i):Array.from({length:12},(_,i)=>i+8))
const weekDays=computed(()=>{const current=dayjs(anchorDate.value),monday=current.subtract((current.day()+6)%7,'day');return Array.from({length:7},(_,i)=>monday.add(i,'day').format('YYYY-MM-DD'))})
const days=computed(()=>viewMode.value==='day'?[dayjs(anchorDate.value).format('YYYY-MM-DD')]:weekDays.value)
const monthDays=computed(()=>{const first=dayjs(anchorDate.value).startOf('month'),start=first.subtract((first.day()+6)%7,'day');return Array.from({length:42},(_,i)=>start.add(i,'day').format('YYYY-MM-DD'))})
const range=computed(()=>viewMode.value==='month'?{start:monthDays.value[0],end:monthDays.value.at(-1)!}:{start:days.value[0],end:days.value.at(-1)!})
const visibleUsers=computed(()=>users.value.filter(item=>(!filter.user_id||item.id===filter.user_id)&&(!filter.department_id||item.department_id===filter.department_id)))
const dateTitle=computed(()=>viewMode.value==='day'?dayjs(days.value[0]).format('YYYY年MM月DD日'):viewMode.value==='week'?`${dayjs(days.value[0]).format('MM月DD日')} - ${dayjs(days.value[6]).format('MM月DD日')}`:dayjs(anchorDate.value).format('YYYY年MM月'))
const batchTasks=computed(()=>tasks.value.filter(item=>!batchForm.project_id||item.project_id===batchForm.project_id))
function daySchedules(date:string){return schedules.value.filter(item=>dayjs(item.start_time).format('YYYY-MM-DD')===date)}
async function load(){loading.value=true;try{const result=await getSchedules({page:1,page_size:500,start_date:range.value.start,end_date:range.value.end,project_id:filter.project_id,user_id:filter.user_id,department_id:filter.department_id});schedules.value=result.items}finally{loading.value=false}}
async function loadOptions(){const[p,t,u,d]=await Promise.all([getProjects({page:1,page_size:200}),getTasks({page:1,page_size:200}),getUserOptions(),getDepartmentOptions()]);projects.value=p.items;tasks.value=t.items;users.value=u;departments.value=d}
function move(step:number){anchorDate.value=dayjs(anchorDate.value).add(step,viewMode.value==='day'?'day':viewMode.value==='week'?'week':'month').format('YYYY-MM-DD');load()}
function openCreate(slot:{userId:number;date:string;hour:number}){if(!userStore.hasPermission('schedule:edit'))return;selected.value=undefined;initialSlot.value=slot;bookingDialog.value=true}
function openDetail(item:Schedule){selected.value=item;detailDialog.value=true}
function openEdit(){detailDialog.value=false;initialSlot.value=undefined;bookingDialog.value=true}
function showConflict(error:unknown){const response=(error as AxiosError<ApiResponse<{conflicts?:ScheduleConflict[]}>>).response;if(response?.status===409&&response.data.data?.conflicts){conflicts.value=response.data.data.conflicts;conflictDialog.value=true;return true}return false}
async function save(payload:SchedulePayload){try{if(selected.value)await updateSchedule(selected.value.id,payload);else await createSchedule(payload);ElMessage.success('预约草稿已保存');bookingDialog.value=false;selected.value=undefined;await load()}catch(error){showConflict(error)}}
async function submit(){if(!selected.value)return;await submitSchedule(selected.value.id);ElMessage.success('预约已提交确认');detailDialog.value=false;await load()}
async function confirm(){if(!selected.value)return;await confirmSchedule(selected.value.id);ElMessage.success('预约已确认');detailDialog.value=false;await load()}
async function reject(){if(!selected.value)return;const{value}=await ElMessageBox.prompt('请输入拒绝原因','拒绝预约',{inputType:'textarea',inputValidator:v=>Boolean(v)||'请填写拒绝原因'});await rejectSchedule(selected.value.id,value);ElMessage.success('预约已拒绝');detailDialog.value=false;await load()}
async function remove(){if(!selected.value)return;await ElMessageBox.confirm('确认删除这条预约吗？','删除预约',{type:'warning'});await deleteSchedule(selected.value.id);ElMessage.success('预约已删除');detailDialog.value=false;await load()}
async function dropToSlot(payload:{scheduleId:number;userId:number;date:string;hour:number}){const item=schedules.value.find(value=>value.id===payload.scheduleId);if(!item||item.user_id!==payload.userId||!userStore.hasPermission('schedule:edit'))return;const duration=dayjs(item.end_time).diff(dayjs(item.start_time),'minute');const start=dayjs(payload.date).hour(payload.hour).minute(dayjs(item.start_time).minute()).second(0);try{await moveSchedule(item.id,{start_time:start.format('YYYY-MM-DD HH:mm:ss'),end_time:start.add(duration,'minute').format('YYYY-MM-DD HH:mm:ss'),expected_version:item.version});ElMessage.success('排期已移动');await load()}catch(error){if(!showConflict(error))ElMessage.error('排期已被更新，请刷新后重试')}}
function startMonthDrag(event:DragEvent,item:Schedule){event.dataTransfer?.setData('schedule-id',String(item.id));if(event.dataTransfer)event.dataTransfer.effectAllowed='move'}
async function dropOnDay(event:DragEvent,date:string){const item=schedules.value.find(value=>value.id===Number(event.dataTransfer?.getData('schedule-id')));if(!item)return;await dropToSlot({scheduleId:item.id,userId:item.user_id,date,hour:dayjs(item.start_time).hour()})}
function openBatch(){batchForm.user_ids=[];batchForm.project_id=projects.value[0]?.id||0;batchForm.task_id=tasks.value.find(item=>item.project_id===batchForm.project_id)?.id||0;batchForm.start_time=dayjs(anchorDate.value).hour(9).minute(0).format('YYYY-MM-DD HH:mm:ss');batchForm.end_time=dayjs(anchorDate.value).hour(17).minute(0).format('YYYY-MM-DD HH:mm:ss');batchForm.remark='';batchDialog.value=true}
async function saveBatch(){if(!batchForm.user_ids.length||!batchForm.project_id||!batchForm.task_id)return ElMessage.warning('请选择人员、项目和任务');batchSaving.value=true;try{const result=await batchCreateSchedules(batchForm);ElMessage.success(`已创建 ${result.created} 条排期草稿`);batchDialog.value=false;await load()}catch(error){showConflict(error)}finally{batchSaving.value=false}}
async function copyPreviousWeek(){if(viewMode.value!=='week')return ElMessage.warning('复制周排期前请切换到周视图');const target=dayjs(weekDays.value[0]);const result=await copyScheduleWeek({source_week_start:target.subtract(7,'day').format('YYYY-MM-DD HH:mm:ss'),target_week_start:target.format('YYYY-MM-DD HH:mm:ss'),user_ids:filter.user_id?[filter.user_id]:undefined});ElMessage.success(`已复制 ${result.created} 条，跳过 ${result.skipped.length} 条冲突记录`);await load()}
const canDecide=computed(()=>selected.value&&['pending','changed'].includes(selected.value.status)&&(selected.value.user_id===userStore.profile?.id||userStore.hasPermission('schedule:edit')))
onMounted(async()=>{await loadOptions();await load()})
</script>

<template>
  <div class="page-shell">
    <header class="page-header"><div><h1 class="page-title">任务共享看板</h1><p class="page-subtitle">日/周/月统一排期，支持拖动调整、批量排期和复制上周安排。</p></div><div class="header-actions" v-if="userStore.hasPermission('schedule:edit')"><el-button @click="copyPreviousWeek">复制上周</el-button><el-button @click="openBatch">批量排期</el-button><el-button type="primary" @click="openCreate({userId:userStore.profile?.id||0,date:anchorDate,hour:9})">创建预约</el-button></div></header>
    <section class="surface board-tools"><div class="filters"><el-select v-model="filter.project_id" clearable filterable placeholder="项目" style="width:190px"><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="filter.user_id" clearable filterable placeholder="人员" style="width:150px"><el-option v-for="item in users" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="filter.department_id" clearable placeholder="部门" style="width:150px"><el-option v-for="item in departments" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-button @click="load">查询</el-button></div><div class="date-nav"><el-button @click="move(-1)">‹</el-button><el-date-picker v-model="anchorDate" value-format="YYYY-MM-DD" :clearable="false" style="width:140px" @change="load"/><el-button @click="move(1)">›</el-button><el-segmented v-model="viewMode" :options="[{label:'日',value:'day'},{label:'周',value:'week'},{label:'月',value:'month'}]" @change="load"/></div></section>
    <section class="surface board-card" v-loading="loading"><div class="board-caption"><strong>{{dateTitle}}</strong><div class="legend"><span class="project">Project</span><span class="routine">Routine</span><span class="training">Training</span><span class="leave">Leave</span></div></div>
      <div v-if="viewMode!=='month'" class="board-scroll"><div class="sticky-header"><div class="person-head">人员</div><ScheduleTimelineHeader :days="days" :hours="hours" :cell-width="cellWidth"/></div><UserScheduleRow v-for="user in visibleUsers" :key="user.id" :user-id="user.id" :user-name="user.name" :days="days" :hours="hours" :cell-width="cellWidth" :schedules="schedules" @blank="openCreate" @booking="openDetail" @drop-booking="dropToSlot"/><el-empty v-if="!visibleUsers.length" description="没有可展示的人员"/></div>
      <div v-else class="month-grid"><div v-for="name in ['一','二','三','四','五','六','日']" :key="name" class="weekday">周{{name}}</div><div v-for="date in monthDays" :key="date" class="month-day" :class="{outside:dayjs(date).month()!==dayjs(anchorDate).month(),today:date===dayjs().format('YYYY-MM-DD')}" @dragover.prevent @drop.prevent="dropOnDay($event,date)" @dblclick="openCreate({userId:userStore.profile?.id||0,date,hour:9})"><span class="day-number">{{dayjs(date).date()}}</span><button v-for="item in daySchedules(date).slice(0,5)" :key="item.id" class="month-booking" draggable="true" @dragstart="startMonthDrag($event,item)" @click.stop="openDetail(item)"><b>{{dayjs(item.start_time).format('HH:mm')}}</b> {{item.user_name}} · {{item.task_name}}</button><small v-if="daySchedules(date).length>5">另有 {{daySchedules(date).length-5}} 条</small></div></div>
    </section>
    <ScheduleBookingDialog v-model="bookingDialog" :initial="selected" :slot="initialSlot" :projects="projects" :tasks="tasks" :users="users" @save="save"/><ScheduleConflictDialog v-model="conflictDialog" :conflicts="conflicts"/>
    <el-dialog v-model="batchDialog" title="批量排期" width="600px"><el-form label-position="top"><el-form-item label="排期人员" required><el-select v-model="batchForm.user_ids" multiple filterable collapse-tags placeholder="可选择多位人员" style="width:100%"><el-option v-for="item in users" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><div class="form-grid"><el-form-item label="项目" required><el-select v-model="batchForm.project_id" filterable style="width:100%" @change="batchForm.task_id=batchTasks[0]?.id||0"><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="任务" required><el-select v-model="batchForm.task_id" filterable style="width:100%"><el-option v-for="item in batchTasks" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></div><div class="form-grid"><el-form-item label="开始"><el-date-picker v-model="batchForm.start_time" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="结束"><el-date-picker v-model="batchForm.end_time" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/></el-form-item></div><el-form-item label="备注"><el-input v-model="batchForm.remark" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="batchDialog=false">取消</el-button><el-button type="primary" :loading="batchSaving" @click="saveBatch">创建草稿</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog" title="预约详情" width="600px"><el-descriptions v-if="selected" :column="2" border><el-descriptions-item label="人员">{{selected.user_name}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag>{{selected.status}}</el-tag></el-descriptions-item><el-descriptions-item label="项目">{{selected.project_name}}</el-descriptions-item><el-descriptions-item label="任务">{{selected.task_name}}</el-descriptions-item><el-descriptions-item label="开始">{{formatDateTime(selected.start_time)}}</el-descriptions-item><el-descriptions-item label="结束">{{formatDateTime(selected.end_time)}}</el-descriptions-item><el-descriptions-item label="预计工时">{{selected.planned_hours}}h</el-descriptions-item><el-descriptions-item label="版本">v{{selected.version}}</el-descriptions-item><el-descriptions-item label="备注" :span="2">{{selected.remark||'—'}}</el-descriptions-item><el-descriptions-item v-if="selected.rejection_reason" label="拒绝原因" :span="2">{{selected.rejection_reason}}</el-descriptions-item></el-descriptions><template #footer><el-button v-if="selected&&['draft','rejected','confirmed'].includes(selected.status)&&userStore.hasPermission('schedule:edit')" @click="openEdit">编辑</el-button><el-button v-if="selected&&['draft','cancelled'].includes(selected.status)&&userStore.hasPermission('schedule:edit')" type="danger" plain @click="remove">删除</el-button><el-button v-if="selected&&['draft','rejected'].includes(selected.status)&&userStore.hasPermission('schedule:edit')" type="primary" @click="submit">提交确认</el-button><el-button v-if="canDecide" type="danger" plain @click="reject">拒绝</el-button><el-button v-if="canDecide" type="success" @click="confirm">同意</el-button></template></el-dialog>
  </div>
</template>

<style scoped>
.header-actions,.filters,.date-nav{display:flex;align-items:center;gap:10px}.board-tools{display:flex;align-items:center;justify-content:space-between;padding:14px 16px}.board-card{overflow:hidden}.board-caption{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-bottom:1px solid #e9edf1;color:#455267;font-size:13px}.legend{display:flex;gap:8px}.legend span{border-radius:6px;padding:4px 7px;background:#dfeaf4;color:#355878;font-size:9px}.legend .routine{background:#e4ece9;color:#48685c}.legend .training{background:#eee9f3;color:#6d587f}.legend .leave{background:#f3e9e8;color:#885d59}.board-scroll{max-height:calc(100vh - 290px);overflow:auto}.sticky-header{position:sticky;top:0;z-index:10;display:flex;width:max-content;min-width:100%;box-shadow:0 2px 6px rgba(39,52,70,.06)}.person-head{position:sticky;left:0;z-index:12;display:grid;width:170px;flex:0 0 170px;place-items:center;border-right:1px solid #e2e6eb;background:#fafbfc;color:#7b8595;font-size:11px}.month-grid{display:grid;grid-template-columns:repeat(7,1fr);max-height:calc(100vh - 290px);overflow:auto}.weekday{position:sticky;top:0;z-index:4;border-right:1px solid #edf0f3;border-bottom:1px solid #e5e9ed;background:#fafbfc;padding:9px;text-align:center;color:#7c8796;font-size:11px}.month-day{min-height:125px;border-right:1px solid #edf0f3;border-bottom:1px solid #edf0f3;padding:7px;background:#fff}.month-day.outside{background:#fafafa;color:#b5bbc3}.month-day.today .day-number{background:#3d6c98;color:#fff}.day-number{display:grid;width:23px;height:23px;place-items:center;border-radius:7px;font-size:11px}.month-booking{display:block;width:100%;overflow:hidden;margin-top:4px;border:0;border-radius:5px;background:#e5edf5;padding:4px 5px;text-align:left;color:#486987;font-size:9px;text-overflow:ellipsis;white-space:nowrap;cursor:grab}.month-booking b{font-weight:650}.month-day>small{display:block;margin-top:4px;color:#8d98a6;font-size:9px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}
</style>
