<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import dayjs from 'dayjs'
import { ElMessage } from 'element-plus'
import { getEvaluation, getProcessReport, getWorkloadReport, updateEvaluation } from '@/api/report'
import { getProjects } from '@/api/project'
import { getUserOptions } from '@/api/user'
import { getDepartmentOptions } from '@/api/organization'
import type { DepartmentOption } from '@/types/organization'
import type { Project } from '@/types/project'
import type { EvaluationPayload, ProcessReportItem, WorkloadItem } from '@/types/report'
import type { UserOption } from '@/types/user'
import { formatDateTime } from '@/utils/format'
import { useUserStore } from '@/stores/user'

const userStore=useUserStore(),activeTab=ref('process'),loading=ref(false),items=ref<ProcessReportItem[]>([]),workloads=ref<WorkloadItem[]>([]),total=ref(0),projects=ref<Project[]>([]),users=ref<UserOption[]>([]),departments=ref<DepartmentOption[]>([])
const query=reactive({page:1,page_size:50,project_id:undefined as number|undefined,owner_id:undefined as number|undefined,start_date:dayjs().startOf('month').format('YYYY-MM-DD'),end_date:dayjs().endOf('month').format('YYYY-MM-DD'),department_id:undefined as number|undefined,user_id:undefined as number|undefined})
const evaluationDialog=ref(false),evaluationTaskId=ref<number>(),evaluationForm=reactive<EvaluationPayload>({achievement_rate:100,achievement_quality:100,comment:''})
async function loadProcess(){loading.value=true;try{const result=await getProcessReport({page:query.page,page_size:query.page_size,project_id:query.project_id,owner_id:query.owner_id,start_date:query.start_date,end_date:query.end_date});items.value=result.items;total.value=result.total}finally{loading.value=false}}
async function loadWorkload(){loading.value=true;try{workloads.value=await getWorkloadReport({start_date:query.start_date,end_date:query.end_date,department_id:query.department_id,user_id:query.user_id})}finally{loading.value=false}}
async function load(){activeTab.value==='process'?await loadProcess():await loadWorkload()}
async function openEvaluation(row:ProcessReportItem){evaluationTaskId.value=row.task_id;const current=await getEvaluation(row.task_id);Object.assign(evaluationForm,current||{achievement_rate:row.achievement_rate??100,achievement_quality:row.achievement_quality??100,comment:''});evaluationDialog.value=true}
async function saveEvaluation(){if(!evaluationTaskId.value)return;await updateEvaluation(evaluationTaskId.value,evaluationForm);ElMessage.success('达成评价已保存');evaluationDialog.value=false;await loadProcess()}
onMounted(async()=>{const[p,u,d]=await Promise.all([getProjects({page:1,page_size:200}),getUserOptions(),getDepartmentOptions()]);projects.value=p.items;users.value=u;departments.value=d;await load()})
</script>

<template>
  <div class="page-shell">
    <header class="page-header"><div><h1 class="page-title">项目过程报表</h1><p class="page-subtitle">对比计划与实际人力，并维护任务达成率和达成质量。</p></div></header>
    <section class="surface report-card"><el-tabs v-model="activeTab" @tab-change="load"><el-tab-pane label="过程报表" name="process"><div class="report-filter"><el-select v-model="query.project_id" clearable filterable placeholder="项目" style="width:190px"><el-option v-for="item in projects" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="query.owner_id" clearable filterable placeholder="负责人" style="width:150px"><el-option v-for="item in users" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-date-picker v-model="query.start_date" type="date" value-format="YYYY-MM-DD" placeholder="开始日期"/><el-date-picker v-model="query.end_date" type="date" value-format="YYYY-MM-DD" placeholder="结束日期"/><el-button @click="query.page=1;loadProcess()">查询</el-button></div><el-table v-loading="loading" :data="items" stripe><el-table-column prop="project_name" label="项目" fixed min-width="150"/><el-table-column prop="level1_task" label="一级任务" fixed min-width="150"/><el-table-column prop="level2_task" label="二级任务" min-width="160"/><el-table-column prop="owner_name" label="负责人" width="100"/><el-table-column label="计划开始" width="145"><template #default="{row}">{{formatDateTime(row.planned_start)}}</template></el-table-column><el-table-column label="计划结束" width="145"><template #default="{row}">{{formatDateTime(row.planned_end)}}</template></el-table-column><el-table-column label="实际开始" width="145"><template #default="{row}">{{formatDateTime(row.actual_start)}}</template></el-table-column><el-table-column label="实际结束" width="145"><template #default="{row}">{{formatDateTime(row.actual_end)}}</template></el-table-column><el-table-column label="预估人力" width="95"><template #default="{row}">{{row.estimated_hours}}h</template></el-table-column><el-table-column label="实际人力" width="95"><template #default="{row}">{{row.actual_hours}}h</template></el-table-column><el-table-column label="达成率" width="90"><template #default="{row}">{{row.achievement_rate==null?'—':`${row.achievement_rate}%`}}</template></el-table-column><el-table-column label="达成质量" width="100"><template #default="{row}">{{row.achievement_quality==null?'—':`${row.achievement_quality}%`}}</template></el-table-column><el-table-column prop="effective_status" label="状态" width="90"/><el-table-column v-if="userStore.hasPermission('evaluation:edit')" label="评价" fixed="right" width="80"><template #default="{row}"><el-button link type="primary" @click="openEvaluation(row)">编辑</el-button></template></el-table-column></el-table><div class="table-footer"><el-pagination v-model:current-page="query.page" v-model:page-size="query.page_size" :total="total" layout="total, sizes, prev, pager, next" @change="loadProcess"/></div></el-tab-pane>
      <el-tab-pane label="人员负载" name="workload"><div class="report-filter"><el-select v-model="query.department_id" clearable placeholder="部门" style="width:160px"><el-option v-for="item in departments" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-select v-model="query.user_id" clearable filterable placeholder="人员" style="width:150px"><el-option v-for="item in users" :key="item.id" :label="item.name" :value="item.id"/></el-select><el-date-picker v-model="query.start_date" type="date" value-format="YYYY-MM-DD"/><el-date-picker v-model="query.end_date" type="date" value-format="YYYY-MM-DD"/><el-button @click="loadWorkload">查询</el-button></div><el-table v-loading="loading" :data="workloads" stripe><el-table-column prop="user_name" label="人员"/><el-table-column prop="date" label="日期"/><el-table-column label="已预约工时"><template #default="{row}">{{row.planned_hours}}h</template></el-table-column><el-table-column label="可用工时"><template #default="{row}">{{row.available_hours}}h</template></el-table-column><el-table-column label="负载率"><template #default="{row}"><el-progress :percentage="Math.min(Number(row.load_rate),100)" :status="row.overloaded?'exception':undefined"><span>{{row.load_rate}}%</span></el-progress></template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.overloaded?'danger':'success'" effect="plain">{{row.overloaded?'过载':'正常'}}</el-tag></template></el-table-column></el-table></el-tab-pane></el-tabs></section>
    <el-dialog v-model="evaluationDialog" title="任务达成评价" width="500px"><el-form :model="evaluationForm" label-position="top"><el-form-item label="达成率"><el-slider v-model="evaluationForm.achievement_rate" show-input :min="0" :max="100"/></el-form-item><el-form-item label="达成质量"><el-slider v-model="evaluationForm.achievement_quality" show-input :min="0" :max="100"/></el-form-item><el-form-item label="评价说明"><el-input v-model="evaluationForm.comment" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="evaluationDialog=false">取消</el-button><el-button type="primary" @click="saveEvaluation">保存评价</el-button></template></el-dialog>
  </div>
</template>

<style scoped>.report-card{padding:8px 18px 18px;overflow:hidden}.report-filter{display:flex;flex-wrap:wrap;gap:10px;margin:6px 0 18px}</style>
